# Generated by Django 3.0.3 on 2020-06-18 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Name of Category')),
                ('description', models.TextField(verbose_name='Describe what this section is about.')),
                ('category_image', models.ImageField(max_length=200, upload_to='images/Category/', verbose_name='Logo for this category')),
                ('slug', models.SlugField(default='default_slug', max_length=200, unique=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_logo', models.ImageField(max_length=200, upload_to='images/Subcategory/', verbose_name='Logo for the subcategory')),
                ('description', models.TextField(verbose_name='Describe what this section is about.')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Name of Sub-Category')),
                ('slug', models.SlugField(default='default_slug', max_length=200, unique=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category', verbose_name='What category does this belong?')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Describe what this section is about.')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Name of Tutorial series')),
                ('tutorial_logo', models.ImageField(max_length=200, upload_to='images/Tutorial/', verbose_name='Logo for tutorial series')),
                ('github_repo_link', models.URLField(max_length=150, verbose_name='Link to github repo')),
                ('tutorial_series_slug', models.SlugField(default='default_slug', max_length=200, unique=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutorial_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.SubCategory', verbose_name='What subcategory does this tutorial belong?')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('youtube_link', models.URLField(max_length=150, verbose_name='Youtube link for uploaded video')),
                ('description', models.TextField(verbose_name='Describe what this section is about.')),
                ('video_title', models.CharField(max_length=40, unique=True, verbose_name='Title of uploaded video')),
                ('tutorial_video_slug', models.SlugField(default='default_slug', max_length=200, unique=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutorial_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Tutorial', verbose_name='What Tutorial series does this belong?')),
            ],
        ),
    ]
