# Generated by Django 3.0.3 on 2020-06-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Your full name (30 characters)')),
                ('email', models.EmailField(max_length=50, verbose_name='Your email address')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
