# Generated by Django 3.0.3 on 2020-06-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_read',
            field=models.BooleanField(default=False),
        ),
    ]
