# Generated by Django 3.0.3 on 2020-07-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20200707_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_series_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tutorialvideo',
            name='tutorial_video_slug',
            field=models.SlugField(unique=True),
        ),
    ]
